composer.json, lib/Conekta/Address.php, lib/Conekta/Card.php, lib/Conekta/Charge.php, lib/Conekta/Conekta.php, lib/Conekta/Customer.php, lib/Conekta/Error.php, lib/Conekta/Event.php, lib/Conekta/Lang.php, lib/Conekta/Log.php, lib/Conekta/Method.php, lib/Conekta/Object.php, lib/Conekta/Payee.php, lib/Conekta/PaymentMethod.php, lib/Conekta/Payout.php, lib/Conekta/PayoutMethod.php, lib/Conekta/Plan.php, lib/Conekta/Requestor.php, lib/Conekta/Resource.php, lib/Conekta/Subscription.php, lib/Conekta/Token.php, lib/Conekta/Util.php, lib/Conekta/Webhook.php, lib/Conekta/WebhookLog.php
- Version most stable for namespaces use
- This version is compatible with PHP 5.3 or greater
- This [issue](https://github.com/conekta/conekta-php/issues/19) is resolved
- [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) use for best PSR-2 performance
=> Stable version for namespaces

lib/Conekta/Requestor.php, lib/Conekta/Resource.php, test/Conekta.php, test/Conekta/OrderTest.php
Better use http_build_query (http://php.net/manual/es/function.http-build-query.php)
than encode method
=> Fix url encoding on get request

lib/Conekta/Resource.php
Regex added in order to correctly call submodel (or any sibling camel cased resource)
=> Underscore added for Order submodes

lib/Conekta.php, lib/Conekta/Customer.php, lib/Conekta/Util.php, test/Conekta.php
- Add ShippingContact model
- Add ShippingContact tests
- Add ShippingContact to customer submodels
=> Add ShippingContact model and tests

lib/Conekta/Order.php, lib/Conekta/ShippingLine.php, test/Conekta.php, test/Conekta/ShippingLineTest.php
- create ShippingLine test
- refactor Order's submodels assgination
=> create ShippingLine test

test/Conekta.php, test/Conekta/DiscountLineTest.php
=> add discount line test

lib/Conekta/Conekta.php, lib/Conekta/Requestor.php, test/Conekta.php, test/Conekta/ConektaTest.php
Also added ConektaTest file in order to test the modifications.
=> Added User Agent modification

lib/Conekta/Requestor.php
Changes to be committed:
modified:   lib/Conekta/Requestor.php
=> Fix Reuqestor.php

lib/Conekta/Object.php
Changes to be committed:
modified:   lib/Conekta/Object.php
=> Fix contextual data parsing when null.

lib/Conekta/ConektaList.php, lib/Conekta/Customer.php, lib/Conekta/FiscalEntity.php, lib/Conekta/Order.php, lib/Conekta/Resource.php, test/Conekta/CustomerTest.php, test/Conekta/OrderTest.php
- Los submodelos no se creaban como ConektaList
- El createMember no regresaba un objeto, regresaba un Array
=> fix conekta lists

test/Conekta-1.0/ChargeTest.php, test/Conekta-1.0/CustomerTest.php
Changes to be committed:
modified:   test/Conekta-1.0/ChargeTest.php
modified:   test/Conekta-1.0/CustomerTest.php
=> Fix 1.0.0 specs

lib/Conekta/ConektaList.php, test/Conekta-2.0/ConektaListTest.php
Fix pagination error on limit value undefined, also it is cover by test method, solve issue https://github.com/conekta/issues/issues/1308
=> Fix pagination

lib/Conekta/ConektaResource.php, lib/Conekta/Exceptions/Handler.php, lib/Conekta/Requestor.php, test/Conekta-1.0/ChargeTest.php, test/Conekta-1.0/CustomerTest.php, test/Conekta-1.0/ErrorTest.php, test/Conekta-2.0/CustomerTest.php, test/Conekta-2.0/DiscountLineTest.php, test/Conekta-2.0/ErrorHandlerTest.php, test/Conekta-2.0/LineItemTest.php, test/Conekta-2.0/OrderTest.php, test/Conekta-2.0/ShippingContactTest.php, test/Conekta-2.0/ShippingLineTest.php, test/Conekta-2.0/SourceTest.php, test/Conekta-2.0/SubscriptionTest.php, test/Conekta-2.0/TaxLineTest.php
All those changes was requested from magento marketplace for php version 7.0 and higher
correct namespaces method  invocation
=> Change: PSR-2 Compliance

README.md
Ya corrí los tests y modifiqué el nombre de la rama
*Por favor no hagan merge hasta que confirmen sus inquietudes, penas y aflicciones conmigo.*
=> [Don't Merge] Modified to correct attribute name

README.md
Hola Conekta:
Buenos días
Mi nombre es Gustavo Martínez y quisiera reportar el siguiente error en la documentación.
Quedo atento a cualquier duda o comentario.
¡Saludos!
=> Fix: Misuse in Finally

test/Conekta-2.0/OrderTest.php
=> Added test for void function

lib/Conekta/Customer.php, test/Conekta-2.0/CustomerTest.php
For consistency with other libraries.
Add the test and the method.
Nothing
=> Add createOfflineRecurrentReference method.

README.md
I've updated the README in order to clarify the contributions section
=> Updating the contribution snippet

.docker/php/Dockerfile, .env.dist, docker-compose.yaml
Add Docker and Docker Compose configuration.
This feature will improve the environtment of testing and development.
PHPUnit and XDebug have been added globally with support for VSCode
=> Docker and Docker composer configuration

CHANGELOG.md, README.md, lib/Conekta.php, lib/Conekta/Checkout.php, lib/Conekta/Conekta.php, lib/Conekta/ConektaResource.php, lib/Conekta/Requestor.php, lib/Conekta/Util.php, test/BaseTest.php, test/Conekta-2.0/CheckoutTest.php, test/Conekta-2.0/OrderTest.php, test/Conekta-2.0/TokenTest.php
Add support to php sdk for
* Create orders with checkout options.
* Create tokens with checkout options.
This PR depend on this another https://github.com/conekta/conekta-php/pull/176
=> [PAYM-1226] php sdk msi via conekta components
